apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "node-app-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "node-app-chart.fullname" . }}-service
            port:
              number: {{ .Values.service.port }}

