apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app-chart.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: TCP
  selector:
    {{- include "node-app-chart.selectorLabels" . | nindent 4 }}
